[general]
import = ["/home/morgan/.config/alacritty/carbonfox/carbonfox.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "PageDown"
mods = "Shift"

[scrolling]
history = 1000
