[icons]
icons = "awesome4"

[theme.overrides]
idle_bg = "#000000"
idle_fg = "#f2f4f8"
good_bg = "#000000"
good_fg = "#be95ff"
warning_bg = "#000000"
warning_fg = "#08bdba"
critical_bg = "#000000"
critical_fg = "#ee5396"
info_bg = "#000000"
info_fg = "#f2f4f8"
separator_bg = "#000000"
separator_fg = "#f2f4f8"

[[block]]
block = "scratchpad"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
full_threshold = 100
empty_threshold = 0
# check for battery
if_command = "[[ -d /sys/class/power_supply/BAT0 ]]"
# keep the same format for all states
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
full_format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
empty_format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
not_charging_format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

[[block]]
block = "vpn"
driver = "mullvad"
format_connected = " vpn $icon  "
format_disconnected = " vpn $icon  "
state_connected = "good"
state_disconnected = "critical"

[[block]]
block = "net"
format = " $icon $device{ $signal_strength $ssid| $ip|} "
[[block.click]]
button = "left"
cmd = "~/.config/sway/toggle_program.sh nm-applet"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %r') "

[[block]]
block = "notify"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "custom"
interval = "once"
command = "echo '\uf205'"
[[block.click]]
button = "left"
cmd = "~/.config/sway/toggle_program.sh waybar -c ~/.config/sway/waytray/config.jsonc -s ~/.config/sway/waytray/style.css"
